### ISSUE TITLE
Output files with different hashes for different locales with version 1.3.0

### ISSUE THREAD

**Issue by ehosaini** [privatenumber/webpack-localize-assets-plugin#33] opened 2021-11-16 18:22 UTC
## Bug description
I am trying to use webpack-localize-assets-plugin alongside html-webpack-plugin. The content hash is unique for each locale-specific file (which takes the form of [name].[locale].[contenthash].js). I downgraded to 1.2.4 version to get the desired outcome (same hash for all the files).

## Reproduction steps
Straightforward usage of both plugins (let me know if more is required).

## Environment

- webpack-localize-asets-plugin version: 1.3.0
- Webpack version: 5.52.0
- Operating System: Windows 10
- Node version: v12.22.5
- Package manager (npm/yarn/pnpm) and version: 6.14.14

**Comment by privatenumber** [comment] 2021-11-16 20:39
That was a bug. `contenthash` should be different because the content is different.

**Comment by privatenumber** [comment] 2021-11-23 23:03
Although this is expected behavior, I will leave this open as I'd like to have better/easier support for `html-webpack-plugin`. Perhaps better documentation to handle or work around the content hash differences.

**Comment by privatenumber** [comment] 2022-12-21 14:38
Closing as the issue has been addressed and there hasn't been progress with the above.

**Closed by privatenumber** 2022-12-21 14:38 UTC
Labels: pr welcome
